@server=http://127.0.0.1:3000

### Connect to terminal 1

POST {{server}}/terminal
Content-Type: application/json

{
  "id": 1,
  "hostname": "data",
  "host": "192.168.0.24",
  "port": 22,
  "username": "aluno",
  "password": "ifpb"
}

### Connect to terminal 2

POST {{server}}/terminal
Content-Type: application/json

{
  "id": 2,
  "host": "192.168.0.24",
  "port": 22,
  "username": "aluno",
  "password": "ifpb"
}